from datetime import datetime,timezone
from sqlalchemy import String,Text,Integer,Boolean,DateTime,Float,ForeignKey,UniqueConstraint
from sqlalchemy.orm import Mapped,mapped_column
from .db import Base
def now(): return datetime.now(timezone.utc)
class Job(Base):
 __tablename__='jobs'; id:Mapped[int]=mapped_column(primary_key=True); external_id:Mapped[str]=mapped_column(String(700),unique=True,index=True); title:Mapped[str]=mapped_column(String(400)); company:Mapped[str]=mapped_column(String(300)); location:Mapped[str]=mapped_column(String(500),default='Worldwide'); salary:Mapped[str]=mapped_column(String(300),default='Not specified'); source:Mapped[str]=mapped_column(String(100)); url:Mapped[str]=mapped_column(String(1200)); apply_url:Mapped[str]=mapped_column(String(1200),default=''); published_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); description:Mapped[str]=mapped_column(Text,default=''); score:Mapped[float]=mapped_column(Float,default=0,index=True); strengths:Mapped[str]=mapped_column(Text,default=''); gaps:Mapped[str]=mapped_column(Text,default=''); risk:Mapped[str]=mapped_column(Text,default=''); recruiter_email:Mapped[str]=mapped_column(String(320),default=''); recruiter_verified:Mapped[bool]=mapped_column(Boolean,default=False); status:Mapped[str]=mapped_column(String(40),default='new'); raw_json:Mapped[str]=mapped_column(Text,default='')
class Application(Base):
 __tablename__='applications'; __table_args__=(UniqueConstraint('job_id',name='uq_application_job'),); id:Mapped[int]=mapped_column(primary_key=True); job_id:Mapped[int]=mapped_column(ForeignKey('jobs.id'),index=True); mode:Mapped[str]=mapped_column(String(30),default='draft'); status:Mapped[str]=mapped_column(String(50),default='draft'); recipient:Mapped[str]=mapped_column(String(320),default=''); subject:Mapped[str]=mapped_column(String(500),default=''); cv_text:Mapped[str]=mapped_column(Text,default=''); cover_letter:Mapped[str]=mapped_column(Text,default=''); gmail_message_id:Mapped[str]=mapped_column(String(300),default=''); gmail_thread_id:Mapped[str]=mapped_column(String(300),default=''); sent_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class ProfileFact(Base):
 __tablename__='profile_facts'; id:Mapped[int]=mapped_column(primary_key=True); category:Mapped[str]=mapped_column(String(100)); fact:Mapped[str]=mapped_column(Text); state:Mapped[str]=mapped_column(String(30),default='verified')
class Message(Base):
 __tablename__='messages'; id:Mapped[int]=mapped_column(primary_key=True); gmail_message_id:Mapped[str]=mapped_column(String(500),unique=True); thread_id:Mapped[str]=mapped_column(String(500),index=True); direction:Mapped[str]=mapped_column(String(20)); sender:Mapped[str]=mapped_column(String(320),default=''); subject:Mapped[str]=mapped_column(String(500),default=''); language:Mapped[str]=mapped_column(String(20),default='en'); body:Mapped[str]=mapped_column(Text,default=''); approval_required:Mapped[bool]=mapped_column(Boolean,default=False); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class AuditEvent(Base):
 __tablename__='audit_events'; id:Mapped[int]=mapped_column(primary_key=True); event:Mapped[str]=mapped_column(String(200)); details:Mapped[str]=mapped_column(Text,default=''); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
